nsfw:
  concepts:
    sexual: 0.18
    nude: 0.19
    sex: 0.206
    18+: 0.21
    naked: 0.195
    nsfw: 0.19
    porn: 0.194
    dick: 0.19
    vagina: 0.19
    naked child: 0.22
    explicit content: 0.19
    uncensored: 0.19
    fuck: 0.195
    nipples: 0.1984
    visible nipples: 0.21
    naked breasts: 0.214
    areola: 0.2
  action: obfuscate
special:
  concepts:
    little girl: 0.2
    little boy: 0.2
    young child: 0.2
    young girl: 0.22
    toddler: 0.2
    baby: 0.2
